import {
  NavigationContextProvider,
  ViewModeContextProvider,
} from '@/shared/providers';
import { fira } from '@/shared/style';
import '@/shared/style/globals.css';

import { NavigationWidget } from '@/widgets/navigation';

// TODO: Figure out viewport settings
import type { Metadata } from 'next';

// TODO: Figure out metdata settings
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={fira.className}>
      <body className="body">
        <NavigationContextProvider>
          <ViewModeContextProvider>{children}</ViewModeContextProvider>
          <NavigationWidget />
        </NavigationContextProvider>
      </body>
    </html>
  );
}
